// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperPartner.Permission.DataContext;

namespace SuperPartner.Migrations
{
    [DbContext(typeof(PermissionDataContext))]
    [Migration("20190726033722_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperPartner.Permission.DataContext.P_Function", b =>
                {
                    b.Property<string>("FuncCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50);

                    b.Property<string>("AssociateUrls")
                        .HasMaxLength(4000);

                    b.Property<string>("ExtendProperties")
                        .HasColumnType("xml");

                    b.Property<string>("FuncDesc")
                        .HasColumnType("ntext");

                    b.Property<string>("FuncName")
                        .HasMaxLength(200);

                    b.HasKey("FuncCode");

                    b.ToTable("P_Functions");
                });

            modelBuilder.Entity("SuperPartner.Permission.DataContext.P_User2Function", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50);

                    b.Property<string>("FuncCode")
                        .HasMaxLength(50);

                    b.Property<int?>("AccessLevel");

                    b.HasKey("UserId", "FuncCode");

                    b.ToTable("P_User2Functions");
                });
#pragma warning restore 612, 618
        }
    }
}
